"""
Django settings for sportcourts project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

IS_PRODUCTION = True

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'o-x00&0e=niyadeseyddr45=!s*@!5xl%)$o-ktbjz8r4lu#k('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if IS_PRODUCTION:
    ALLOWED_HOSTS = ['test.sportcourts.ru', 'sportcourts.ru', '127.0.0.1', '127.0.0.1:8001']
else:
    ALLOWED_HOSTS = ['test.sportcourts.ru', 'sportcourts.ru', '127.0.0.1']


# Application definition

INSTALLED_APPS = (
    # TODO: think about admin https://github.com/sshwsfc/django-xadmin
    'bootstrap_admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sorl.thumbnail',
    'bootstrap3',
    'customuser',
    'notifications',
    'courts',
    'events',
    'teams',
    'finances',
    'blog',
    'utils',
    'rest_framework',
    'django_cleanup', # should go after your apps | delete orphaned old files
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'sportcourts.urls'

WSGI_APPLICATION = 'sportcourts.wsgi.application'

AUTH_USER_MODEL = 'customuser.User'
LOGIN_URL = '/login'
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

VKONTAKTE = {
    'SECRET': 'SyrEE8fNLlkCBUxuxwTL',
    'APPID': '4963792'
}

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'info@sportcourts.ru'
EMAIL_HOST_PASSWORD = 'courtssport2'
EMAIL_SUBJECT_PREFIX = '[SPORTCOURTS] '
ADMINS = ('Vitaliy', 'harchenko.grape@gmail.com')

YANDEX_MAPS_API_KEY = 'ADtA-FMBAAAAO_95dwIAb8cxoJ0XVsmlrrEljkqDE8QIFgsAAAAAAAAAAADwojBjdahSnZySk0zChxiVovWqNw=='

if IS_PRODUCTION:
    CURRENT_HOST = 'test.sportcourts.ru'
else:
    CURRENT_HOST = '127.0.0.1:8000'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases


if IS_PRODUCTION:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'scdb',
            'USER': 'scuser',
            'PASSWORD': '4203',
            'HOST': 'localhost',
            'PORT': '',
    }
}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'sc',
            'HOST': 'localhost',
            'PASSWORD': '4203',
            'USER': 'sc'
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Asia/Yekaterinburg'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

if IS_PRODUCTION:
    STATIC_URL = '/static/'
    STATIC_ROOT = '/opt/scenv/static/'
    STATICFILES_DIRS = (
        os.path.join(BASE_DIR, 'static'),
    )
else:
    STATIC_URL = '/static/'
    STATIC_ROOT = '/static/'
    STATICFILES_DIRS = (
        os.path.join(BASE_DIR, 'static'),
    )

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

TEMPLATE_DIRS = (
    os.path.join(BASE_DIR,  'templates'),
)

TEMPLATE_CONTEXT_PROCESSORS = (
    "django.contrib.auth.context_processors.auth",
    "django.template.context_processors.debug",
    "django.template.context_processors.i18n",
    "django.template.context_processors.media",
    "django.template.context_processors.static",
    "django.template.context_processors.tz",
    "django.contrib.messages.context_processors.messages",
    "django.core.context_processors.request",
    "customuser.loggedin_user_context_processor",
    "sportcourts.context_processors.variables",
    "customuser.context_processors.userforms",
    "notifications.context_processors.notifications"
)